import type { Metadata } from "next";
import "./globals.css";
import { QuizProvider } from "../components/QuizProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className={`antialiased`}>
                <QuizProvider>{children}</QuizProvider>
            </body>
        </html>
    );
}
